name: fitcontrolgym-landing

services:
  fitcontrolgym-landing:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8083:80"
    networks:
      - web_network

networks:
  web_network:
    external: true
